manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zampierilucas
    - name: efogdev
      url-base: https://github.com/efogdev
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/individual-hid-battery-reporting
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: zephyr-4.1
  self:
    path: config
